Django--master/-Django--master/网上购书系统/bookshop/Shop/urls.py
from django.urls import path,re_path
from . import views

urlpatterns = [
    path('index/', views.index, name='index'),        # 主页
    path('detail/', views.prodetail, name='detail'),  # 详细页面
    path('addtocart/', views.addtocart, name='addtocart'), # 添加到购物车
    path('getcartnum1/', views.getcartnum, name='getcartnum'),  # 添加到购物车
    path('showcart/',views.showCart,name='showcart'), # 展示购物车
    path('addgoods1/',views.add_goods,name='addgoods'),
    path('subgoods1/',views.sub_goods,name='subgoods'),
    path('deletcart/',views.delCart,name='deletcart'),  # 删除购物车的商品
    path('cash_pay/',views.cash_payment,name='cash_pay'),  # 支付

]
app_name = 'bShop'

Django--master/-Django--master/网上购书系统/bookshop/bookshop/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [

    # path('admin/', admin.site.urls),

    path('user/',include('User.urls')),
    path('shop/',include('Shop.urls')),
    path('admin/', include('adminuser.urls')),
]

Django--master/-Django--master/网上购书系统/bookshop/templates/bshop/ShowCart.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <link rel="stylesheet" type="text/css" href="/static/css/foot.css">
     <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/showcat.css">
    <script src="{% static 'admin/js/html5.js' %}"></script>
    <script type="text/javascript" src="../../static/js/ie6.js"></script>
    <script src="{% static 'admin/js/jquery.js' %}"></script>
     <script type="text/javascript"   src="{% static 'js/common.js' %}"></script>
     <script type="text/javascript"   src="{% static 'js2/ShowCat.js' %}"></script>
   <script>
       function addgoods(id) {
           var cookieop = new cookieOperate();
           var csrf = cookieop.getCookie('csrftoken');
           $.ajax({
                    url: '/shop/addgoods1/',
                    type: 'POST',
                     data: {'product_pid': id},

                     beforeSend: function (request) {
                            request.setRequestHeader("X-CSRFToken", csrf);
                        },
                     success: function (data) {
                       window.location = window.location;
                   },
                    error:function (data) {
                      alert("失败")
                    }
                 });
            }
            function subgoods(id) {
           var cookieop = new cookieOperate();
           var csrf = cookieop.getCookie('csrftoken');
           $.ajax({
                    url: '/shop/subgoods1/',
                    type: 'POST',
                     data: {'product_pid': id},

                     beforeSend: function (request) {
                            request.setRequestHeader("X-CSRFToken", csrf);
                        },
                     success: function (data) {
                       window.location = window.location;
                   },
                    error:function (data) {
                      alert("亲，别删光啊")
                    }
                 });
            }
   </script>
    <script>
           $(function () {
               $('#jiesuan').click(function () {
                    var cartlist ="";
               $('.onecheck:checked').each(function(i) {
                    cartlist+= parseFloat($(this).parents("ul ").find('.cat_cid').val());
                    cartlist+="#"
                 })
                   $('#cartlist').val(cartlist);
                    $('#payform').submit();
               });
           });
    </script>
</head>
<body>
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到图书商城</div>
			<div class="fr">
				<div class="login_btn fl">
					{% if userinfo.islogin %}
					欢迎您：<em>{{ userinfo.username }}</em>
					<span>|</span>
					<a href="{% url 'bUser :logout' %}">退出</a>
					{% else %}
					<a href="{% url 'bUser :login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'bUser :register' %}">注册</a>
					{% endif %}
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'bUser :personalinfo' %}">用户中心</a>
					<span>|</span>
				    <a href="{% url 'bShop:showcart' %}">我的购物车</a>
					<span>|</span>
					<a href="#">我的订单</a>
				</div>
			</div>
		</div>
     </div>
    <div class="search_bar clearfix">
		<a href="{% url 'bShop:index' %}" class="logo fl"><img src="{% static '/images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
	</div>
    <div class="total_count">全部商品<em>{{ allcartnum }}</em>种</div>
    <ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品定价</li>
        <li class="col03">商品折扣</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
     <form id="payform" method="post" action="{% url 'bShop:cash_pay' %}" id="cartform">
     {% csrf_token %}
     <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
      {% for cat in allcart %}
    <ul class="cart_list_td clearfix" id="436">
        <li class="col01"><input type="checkbox" class="onecheck" checked ></li>

                 <input type="hidden" name="pid[]"  value="{{ cat.product_id }}">
                   <input type="hidden" class="cat_cid"  value="{{ cat.cid }}">
                  <li class="col02">  <img src="{{ cat.product.pdImage }}"></li>
                  <li class="col03">{{ cat.product.pdname}}</li>
                  <li class="col04">{{ cat.product.pdprice }}元</li>
                   <li class="col05">{{ cat.product.discount}}折</li>
                    <li class="col06">
			     <div class="num_add">
                 <a href="javascript:;"   class="add fl" onclick="addgoods({{ cat.product_id }})">+</a>
                <input type="text" class="num_show  fl" value="{{ cat.pnum }}">
				<a href="javascript:;"  class="minus fl" onclick="subgoods({{ cat.product_id  }})">-</a>
			</div>
		    </li>
    <li class="col07"><em id="price">{{ cat.sumprice }} </em>元</li>
    <li class="col08"><a href="{% url 'bShop:deletcart' %}?pid={{ cat.product_id }}">删除</a></li>
	</ul>
    {% endfor %}
         <input type="text" id="cartlist" name="cartlist" value="">
    <ul class="settlements">
		<li class="col01"><input type="checkbox" id="allcheck" checked  ></li>
		<li class="col02">全选</li>
		<li class="col03">合计(包邮)：<span>¥</span><em id="zong">0</em> <br>共计<b id="zongshu"></b>件商品</li>
		<li class="col04"><a href="javascript:;" id="jiesuan" style="background-color: rgb(255, 61, 61);">去结算</a></li>
	</ul>
     </form>
   <div class="center_con clearfix">
     <div class="footer_nav_box">
        <div class="footer_nav">
            <a href="#" target="_blank" rel="nofollow">公司简介</a>
            <span class="sep">|</span>
            <a href="#" target="_blank">诚聘英才</a>
            <span class="sep">|</span>
            <a href="#" target="_blank">图书商城</a>
            <span class="sep">|</span>
            <a href="#" target="_blank">网站联盟</a>
            <span class="sep">|</span>
            <a href="#" target="_blank">官方Blog</a>
        </div>
        <div class="footer_copyright">
            <span>Copyright (C) 当当网 2004-2017, All Rights Reserved</span>
        </div>
        <div class="clear"></div>
     </div>
    </div>

   <script>
     $(function () {
        $("#allcheck").click(function() {
        var flag = $(this).prop("checked");
        if(flag) {
            $(".onecheck").prop("checked", true);
        } else {
            $(".onecheck").prop("checked", false);

        }
        totalPrice();
        counts();
      });

        //单选
    $(".onecheck").click(function() {

        var CL = $(".onecheck").length; //列表长度；
        var CH = $(".onecheck:checked").length; //列表中被选中的长度

        if(CL == CH) {
            $("#allcheck").prop("checked", true);

        } else {
            $("#allcheck").prop("checked", false);

        }

        totalPrice();
        counts();
    })
         //总价格
    totalPrice();

    function totalPrice() {
        var prices = 0;
        $('.onecheck:checked').each(function(i) {
            console.log()
            prices += parseFloat($(this).parents("ul ").find('#price').text());
        })
        $('#zong').text(prices);
    }

    //总数目
    counts();

    function counts() {
        var sum = 0;
        $('.onecheck:checked').each(function(i) {
            sum += parseInt($(this).parents("ul").find('.num_show').val());
        })
        $('#zongshu').text(sum);
    }

 });

   </script>

</body>
</html>

Django--master/-Django--master/网上购书系统/bookshop/templates/bshop/detail1.html
<!DOCTYPE html>
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
        <link rel="stylesheet" type="text/css" href="/static/css/detail.css">
       <link rel="stylesheet" type="text/css" href="/static/css/foot.css">
     <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/foot.css">
    {% comment %}<script type="text/JavaScript" src="{% static 'admin/js/html5.js' %}"></script>
    <script type="text/javascript" src="../../static/js/ie6.js"></script>{% endcomment %}
    <script type="text/JavaScript" src="{% static 'admin/js/jquery.js' %}"></script>
     <script type="text/JavaScript" src="{% static 'js2/detail.js' %}"></script>
        <script type="text/javascript" src="{% static 'js2/test.js' %}"></script>
    <script type="text/javascript"   src="{% static 'js/common.js' %}"></script>



</head>
<body>
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到图书商城</div>
			<div class="fr">
				<div class="login_btn fl">
					{% if userinfo.islogin %}
					欢迎您：<em>{{ userinfo.username }}</em>
					<span>|</span>
					<a href="{% url 'bUser :logout' %}">退出</a>
					{% else %}
					<a href="{% url 'bUser :login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'bUser :register' %}">注册</a>
					{% endif %}
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'bUser :personalinfo' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'bShop:showcart' %}">我的购物车</a>
					<span>|</span>
					<a href="#">我的订单</a>
				</div>
			</div>
		</div>
     </div>
    <div class="search_bar clearfix">
		<a href="{% url 'bShop:index' %}" class="logo fl"><img src="{% static '/images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'bShop:showcart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">0</div>
		</div>
	</div>

     <div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
            <span></span>


		</div>
	</div>
     <div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ category.kind }}</a>
		<span>></span>
		<span>商品详情</span>
	</div>
    <div class="goods_detail_con clearfix">
       <!--产品简介-->
        <div id="product_intro">
            <div id="preview">
                <p id="medimImgContainer">
                    {% with imgl=product.pdImage%}
                          <img id="mediumImg" src="{{ imgl}}"/>
                    {% endwith %}
                    <span id="mask"></span><!--小黄块-->
                    <span id="maskTop"></span><!--悬于图片/mask上方的专用于接收鼠标移动事件的一个完全透明的层-->
                     <span id="largeImgContainer">
                        <img id="loading" src="{% static 'images/loading.gif' %}"/>
                        <img id="largeImg"/>
                     </span>
                  </p>
                 <h1>
                    <a class="backward_disabled"></a>
                    <a class="forward_disabled"></a>
                    <div>
                        <ul id="icon_list">
                            {% for item in imglist  %}
                                <li><img src="{{ item }}"/></li>
                            {% endfor %}
                        </ul>
                    </div>
                 </h1>
            </div>
            <form method="post" action="#">
                {% csrf_token %}
             	<div class="goods_detail_list fr">
                    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                       <input type="hidden" name="pid[]" value="{{ product.pid }}">
                    <h3>{{ product.pdname}}</h3>
                    <div class="prize_bar">
                        <span class="show_pirze2">¥<em id="danjia">{{ price }}</em><em>({{  product.discount}}折)</em></span>
                        <span class="show_pirze">定价: ¥<em>{{ product.pdprice }}</em></span>
                     </div>
                     <div class="goods_num clearfix">
                         <div class="num_name fl">数 量：</div>
                            <div class="num_add fl">
                                <input type="text" class="num_show_{{ product.pid }} fl" id="shuliang" value="1">
                                <a href="javascript:;" class="add fr" id="jiahao">+</a>
                                <a href="javascript:;"  class="minus fr" id="jianhao">-</a>
				            </div>
			            </div>
                       <div class="total">总价：<em class="price{{  product.pid  }} " id="zongjia" >{{ price }}</em> <em>元</em></div>
                        <div class="operate_btn">
				            <a href="#" class="buy_btn">立即购买</a>
				            <a href="javascript:;"  class="add_cart" id="add_cart">加入购物车<i class="cart"></i></a>
			            </div>
                      </div>

            </form>
      </div>



        </div>

	</div>

{#    图书展区#}
    <div class="product_content clearfix">
        {#    右边主体#}
        <div id="right-content" class="main">
            <div id="buyTogether" class="group_buy" dd_name="最佳拍档">
                <ul class="tab clearfix">
                    <li class="hover" data-type="buyTogether">产品介绍</li>
                </ul>
                 <div class="over">
                     <span>{{ product.pdInfo }}</span>

                </div>

            </div>


        </div>
        {#    左侧主体#}
        <div class="aside">
            <div id="alsoVies" class="abox">
                <h3>同类型推荐</h3>
                <ul class="none_b listo1 list_alsoview">
                    {% for book in books%}
                        {% if book.pid != product.pid%}
                    <li>
                     {% with imgl=book.pdImage %}
                        <p class="pic">
                            <a href="{% url 'bShop:detail' %}?pid={{ book.pid }}" target="_blank">
                                <img src="{{ imgl }}" alt="">
                            </a>
                        </p>
                     {% endwith %}
                        <p class="price">
                            <span class="price_d">¥{{ book.pdprice }}</span>
                        </p>
                        <p class="name">
                            <p class="pdname">{{ book.pdname }}</p>
                        </p>
                        <p class="bottom_product"></p>
                    </li>
                        {% endif %}
                    {% endfor %}

                </ul>
            </div>

        </div>


    </div>
     <div class="footer_nav_box">
        <div class="footer_nav">
            <a href="#" target="_blank" rel="nofollow">公司简介</a>
            <span class="sep">|</span>
            <a href="#" target="_blank">诚聘英才</a>
            <span class="sep">|</span>
            <a href="#" target="_blank">图书商城</a>
            <span class="sep">|</span>
            <a href="#" target="_blank">网站联盟</a>
            <span class="sep">|</span>
            <a href="#" target="_blank">官方Blog</a>
        </div>
        <div class="footer_copyright">
            <span>Copyright (C) 当当网 2004-2017, All Rights Reserved</span>
        </div>

        <!-- 有三个icon的时候加footer_icon2 -->
{#        <div class="footer_icon footer_icon2" style="padding-left: 55px;">#}
{#            <div class="validator"><a href="#" target="_blank" class="footer_img"><img src="../../static/images/validate.gif"></a></div>#}
{#            <div class="validator"><a href="#" target="_blank" class="footer_img"><img src="../../static/images/validate.gif"></a></div>#}
{#            <div class="validator"><a id="_pingansec_bottomimagesmall_brand" href="#"  target="_blank"><img src="../../static/images/validate.gif"></a></div>#}
{#        </div>#}
        <div class="clear"></div>
    </div>





</body>
</html>

Django--master/-Django--master/网上购书系统/bookshop/templates/bshop/index.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <link rel="stylesheet" type="text/css" href="/static/css/foot.css">
     <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <script src="{% static 'admin/js/html5.js' %}"></script>
    <script type="text/javascript" src="../../static/js/ie6.js"></script>
    <script src="{% static 'admin/js/jquery.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>


</head>
<body>
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到图书商城</div>
			<div class="fr">
				<div class="login_btn fl">
					{% if userinfo.islogin %}
					欢迎您：<em>{{ userinfo.username }}</em>
					<span>|</span>
					<a href="{% url 'bUser :logout' %}">退出</a>
					{% else %}
					<a href="{% url 'bUser :login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'bUser :register' %}">注册</a>
					{% endif %}
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'bUser :personalinfo' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'bShop:showcart' %}">我的购物车</a>
					<span>|</span>
					<a href="#">我的订单</a>
				</div>
			</div>
		</div>
     </div>
     <div class="search_bar clearfix">
		<a href="{% url 'bShop:index' %}" class="logo fl"><img src="{% static '/images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'bShop:showcart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">0</div>
		</div>
	</div>


     <div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>

		</div>
	</div>

   <div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#" >学习书刊</a></li>
			<li><a href="#" >小说书刊</a></li>
			<li><a href="#" >时尚杂志</a></li>
			<li><a href="#" >儿童书刊</a></li>
			<li><a href="#" >明星传记</a></li>
			<li><a href="#" >励志书刊</a></li>
		</ul>
         <div class="container">
            <div class="wrap"  style="left:-802px;">
                <img src="{% static '/images/5.webp' %}">
                <img src="{% static '/images/1.webp' %}">
                <img src="{% static '/images/2.webp' %}">
                <img src="{% static '/images/3.webp' %}">
                <img src="{% static '/images/4.webp' %}">
                 <img src="{% static '/images/5.webp' %}">
                <img src="{% static '/images/1.webp' %}">
            </div>
             <ul class="tab-nav" style="margin-left: -78px; display: block;">
                <s class="nav-item" data-tab-idx="0"></s>
                <s class="nav-item " data-tab-idx="1"></s>
                <s class="nav-item" data-tab-idx="2"></s>
                <s class="nav-item" data-tab-idx="3"></s>
                <s class="nav-item" data-tab-idx="4"></s>

             </ul>
            <div class="tab-prev" id='tab-prev'contenteditable="true"></div>
            <div class="tab-next" id='tab-next'contenteditable="true"></div>
         </div>
         <div class="right_body">
              <img src="{% static '/images/6.jpg' %}">
             <img id="top_img" src="{% static '/images/7.jpg' %}">

         </div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">学习书刊</h3>
			<div class="subtitle fl">
				<span>|</span>
			</div>
			<a href="#" class="goods_more fr" >查看更多 ></a>
		</div>

		<div class="goods_con clearfix">

			<ul  class="goods_list fl">
               <span></span>
				{% for book1 in book1s%}
				<li>

					<h4><a href="{% url 'bShop:detail' %}?pid={{ book1.pid }}">{{ book1.pdname}}</a></h4>
                    {% with imgl=book1.pdImage %}
                        <a href="{% url 'bShop:detail' %}?pid={{ book1.pid }}"><img src="{{ imgl }}"></a>
                    {% endwith %}
					<div class="prize">¥ {{ book1.pdprice }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>

	</div>

   <div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">小说书刊</h3>
			<div class="subtitle fl">
				<span>|</span>
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>


		<div class="goods_con clearfix">

			<ul  class="goods_list fl">
               <span></span>
				{% for book2 in book2s%}
				<li>
					<h4><a href="{% url 'bShop:detail' %}?pid={{ book2.pid }}">{{ book2.pdname}}</a></h4>
                    {% with imgl2=book2.pdImage %}
                        <a href="{% url 'bShop:detail' %}?pid={{ book2.pid }}"><img src="{{ imgl2 }}"></a>
                    {% endwith %}
					<div class="prize">¥ {{ book2.pdprice }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>

	</div>
   <div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">时尚杂志</h3>
			<div class="subtitle fl">
				<span>|</span>
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>


		<div class="goods_con clearfix">

			<ul  class="goods_list fl">
               <span></span>
				{% for book3 in book3s%}
				<li>
					<h4><a href="{% url 'bShop:detail' %}?pid={{ book3.pid }}">{{ book3.pdname}}</a></h4>
                    {% with imgl3=book3.pdImage %}
                        <a href="{% url 'bShop:detail' %}?pid={{ book3.pid }}"><img src="{{ imgl3 }}"></a>
                    {% endwith %}
					<div class="prize">¥ {{ book3.pdprice }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>

	</div>
   <div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">儿童书刊</h3>
			<div class="subtitle fl">
				<span>|</span>
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>


		<div class="goods_con clearfix">

			<ul  class="goods_list fl">
               <span></span>
				{% for book4 in book4s%}
				<li>
					<h4><a href="{% url 'bShop:detail' %}?pid={{ book4.pid }}">{{ book4.pdname}}</a></h4>
                    {% with imgl4=book4.pdImage %}
                        <a href="{% url 'bShop:detail' %}?pid={{ book4.pid }}"><img src="{{ imgl4 }}"></a>
                    {% endwith %}
					<div class="prize">¥ {{ book4.pdprice }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>

	</div>
   <div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">明星传记</h3>
			<div class="subtitle fl">
				<span>|</span>
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>


		<div class="goods_con clearfix">

			<ul  class="goods_list fl">
               <span></span>
				{% for book5 in book5s%}
				<li>
					<h4><a href="{% url 'bShop:detail' %}?pid={{ book5.pid }}">{{ book5.pdname}}</a></h4>
                    {% with imgl5=book5.pdImage %}
                        <a href="{% url 'bShop:detail' %}?pid={{ book5.pid }}"><img src="{{ imgl5 }}"></a>
                    {% endwith %}
					<div class="prize">¥ {{ book5.pdprice }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>

	</div>
     <div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">励志书刊</h3>
			<div class="subtitle fl">
				<span>|</span>
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>


		<div class="goods_con clearfix">

			<ul  class="goods_list fl">
               <span></span>
				{% for book6 in book6s%}
				<li>
					<h4><a href="{% url 'bShop:detail' %}?pid={{ book6.pid }}">{{ book6.pdname}}</a></h4>
                    {% with imgl6=book6.pdImage %}
                        <a href="{% url 'bShop:detail' %}?pid={{ book6.pid }}"><img src="{{ imgl6 }}"></a>
                    {% endwith %}
					<div class="prize">¥ {{ book6.pdprice }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>

	</div>
   <div class="footer_nav_box">
        <div class="footer_nav">
            <a href="#" target="_blank" rel="nofollow">公司简介</a>
            <span class="sep">|</span>
            <a href="#" target="_blank">诚聘英才</a>
            <span class="sep">|</span>
            <a href="#" target="_blank">图书商城</a>
            <span class="sep">|</span>
            <a href="#" target="_blank">网站联盟</a>
            <span class="sep">|</span>
            <a href="#" target="_blank">官方Blog</a>
        </div>
        <div class="footer_copyright">
            <span>Copyright (C) 当当网 2004-2017, All Rights Reserved</span>
        </div>

        <!-- 有三个icon的时候加footer_icon2 -->
{#        <div class="footer_icon footer_icon2" style="padding-left: 55px;">#}
{#            <div class="validator"><a href="#" target="_blank" class="footer_img"><img src="../../static/images/validate.gif"></a></div>#}
{#            <div class="validator"><a href="#" target="_blank" class="footer_img"><img src="../../static/images/validate.gif"></a></div>#}
{#            <div class="validator"><a id="_pingansec_bottomimagesmall_brand" href="#"  target="_blank"><img src="../../static/images/validate.gif"></a></div>#}
{#        </div>#}
        <div class="clear"></div>
    </div>
   <script type="text/javascript"   src="{% static 'js/common.js' %}"></script>
</body>
</html>